# -*- coding: utf-8 -*-
"""helper_functions.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mFn9QKNEnHdh-UPWmnNe27O7Q-dazy22
"""

# all dependencies 

import matplotlib.pyplot as plt

# Plot validation and loss curves for training and validation metrics

def plot_loss_curves(history):
  """
  Returns separate loss curves for training and validation metrics.
  
  Args:
    history: Tensorflow History object compiled with accuracy metrics only.

  Returns:
    Plots of training / validation loss and accuracy metrics.
  """

  loss = history.history["loss"]
  val_loss = history.history["val_loss"]

  accuracy = history.history["accuracy"]
  val_accuracy = history.history["val_accuracy"]

  epochs = range(len(loss))

  # Plot loss
  plt.plot(epochs, loss, label = "Training Loss")
  plt.plot(epochs, val_loss, label = "Validation Loss")

  plt.title("Loss")
  plt.xlabel("Epochs")
  plt.legend()

  # Plot accuracy
  #plt.figure()
  plt.plot(epochs, accuracy, label = "Training accuracy")
  plt.plot(epochs, val_accuracy, label = "Validation accuracy")
  plt.title ("Accuracy")
  plt.xlabel ("Epochs")
  plt.legend()

